export default [
  {
    text: '浏览器',
    collapsed: false,
    items: [
      { text: 'DOM 操作', link: '/fe/browser/dom' },
      { text: '事件处理', link: '/fe/browser/event' },
      { text: 'Observer', link: '/fe/browser/observer' },
      // { text: '事件循环', link: '/fe/browser/event-loop' },
      // { text: '存储', link: '/fe/browser/storage' },
      // { text: '跨标签页通信', link: '/fe/browser/multiple-tags' },
      { text: '渐进式 WEB 应用', link: '/fe/browser/pwa' },
    ],
  },
  {
    text: 'JavaScript',
    collapsed: true,
    items: [
      { text: '模块化', link: '/fe/js/module' },
      // { text: '位运算符', link: '/fe/js/bitwise' },
      { text: '异步编程', link: '/fe/js/async' },
      { text: '正则表达式', link: '/fe/js/RegExp' },
      // { text: '设计模式', link: '/fe/js/design-pattern' },
      { text: '工具函数', link: '/fe/js/utils' },
    ],
  },
  {
    text: '网络',
    collapsed: true,
    items: [
      { text: 'HTTP', link: '/fe/network/http' },
      { text: '缓存', link: '/fe/network/cache' },
      // { text: 'HTTPS', link: '/fe/network/https' },
      { text: 'AJAX', link: '/fe/network/ajax' },
      { text: 'CORS', link: '/fe/network/cors' },
      // { text: 'CDN', link: '/fe/network/cdn' },
      // { text: 'Cookie & Session', link: '/fe/network/cookie-session' },
      // { text: '网络安全', link: '/fe/network/security' },
      // { text: '性能优化', link: '/fe/network/performance-optimization' },
      { text: 'SSE', link: '/fe/network/sse' },
      // { text: 'WebSocket', link: '/fe/network/websocket' }
    ],
  },
  {
    text: 'Vue',
    collapsed: true,
    items: [
      { text: '组件', link: '/fe/vue/component' },
      { text: '组件通信', link: '/fe/vue/component-communicate' },
      { text: '状态管理 Pinia', link: '/fe/vue/pinia' },
      { text: '路由管理 VueRouter', link: '/fe/vue/router' },
      { text: 'CSS 功能', link: '/fe/vue/css' },
      { text: 'h 函数', link: '/fe/vue/h' },
      { text: '实践场景', link: '/fe/vue/practice' },
    ],
  },
  {
    text: 'Node.js',
    collapsed: true,
    items: [
      { text: '使用 nvm 管理 node', link: '/fe/node/nvm' },
      { text: 'npm 包管理器', link: '/fe/node/npm' },
      // { text: '包管理器的差异', link: '/fe/node/pkg-manager-diff' },
      { text: 'package.json', link: '/fe/node/package-json' },
      { text: '全局变量', link: '/fe/node/globals' },
      { text: '常用内置模块', link: '/fe/node/api' },
      // { text: '流', link: '/fe/node/stream' },
      // { text: '事件循环', link: '/fe/node/event-loop' },
      { text: 'Express 基本使用', link: '/fe/node/express' },
      { text: 'Express 常见场景', link: '/fe/node/express-scene' },
    ],
  },
  {
    text: '工程化',
    collapsed: true,
    items: [
      { text: 'Vite 基本使用', link: '/fe/engineering/vite' },
      { text: '性能优化', link: '/fe/engineering/performance' },
      // { text: 'JS', link: '/fe/engineering/js' },
      // { text: 'CSS', link: '/fe/engineering/css' },
      // { text: 'ICON', link: '/fe/engineering/icon' },
      // { text: 'Git', link: '/fe/engineering/git' },
    ],
  },
]
